#!/usr/bin/env python3

# python make_workload.py \
#   --table salary \
#   --column salary \
#   --out workload/workload_100.sql \
#   --n-equality 50 \
#   --n-range 50 \
#   --min 30000 \
#   --max 300000

import argparse, math, random
from pathlib import Path
import numpy as np

# ----------------------------
# helpers
# ----------------------------
def clamp_int(x, lo, hi):
    return int(min(max(int(round(x)), lo), hi))

def parse_mix(mix_str):
    """
    Parse mix like: 'uniform:0.25,normal:0.2,laplace:0.15,student_t:0.1,lognormal:0.15,pareto:0.075,zipf:0.075'
    Returns (names, probs) normalized.
    """
    items = [p.strip() for p in mix_str.split(",") if p.strip()]
    pairs = []
    for it in items:
        name, w = it.split(":")
        pairs.append((name.strip(), float(w)))
    total = sum(w for _, w in pairs)
    names = [n for n, _ in pairs]
    probs = [w/total for _, w in pairs]
    return names, probs

def choose_dist(rng, names, probs):
    return rng.choice(len(names), p=probs)

def sample_value(dist_name, rng, lo, hi, mid, span):
    """Return a single int in [lo, hi] according to dist_name."""
    if dist_name == "uniform":
        v = rng.integers(lo, hi + 1)
    elif dist_name == "normal":
        v = rng.normal(loc=mid, scale=span/6.0)  # ~99.7% in +/- 3 sigma
    elif dist_name == "laplace":
        v = rng.laplace(loc=mid, scale=span/10.0)
    elif dist_name == "student_t":
        v = mid + (span/10.0) * rng.standard_t(df=3.0)
    elif dist_name == "lognormal":
        # choose sigma for skew; center so median ~ mid
        sigma = 0.8
        v = math.exp(rng.normal(loc=math.log(max(mid,1)), scale=sigma))
    elif dist_name == "pareto":
        alpha = 2.0
        xm = max(lo, 1)
        v = xm * (1.0 + rng.pareto(alpha))
    elif dist_name == "zipf":
        a = 2.0
        z = rng.zipf(a)
        v = lo + z  # clamp will cap it
    else:
        v = rng.integers(lo, hi + 1)
    return clamp_int(v, lo, hi)

def sample_range(dist_name, rng, lo, hi, mid, span):
    """
    Sample a BETWEEN range.
    Strategy: pick a center using dist_name, then a half-width as a fraction of domain (beta),
    clamp into [lo, hi], and ensure lo <= hi with at least 1 width when possible.
    """
    c = sample_value(dist_name, rng, lo, hi, mid, span)
    # half-width fraction biased to smaller ranges; adjust to taste
    half_frac = rng.beta(2.0, 5.0)
    half_width = max(1, int(half_frac * (span / 4)))
    a = clamp_int(c - half_width, lo, hi)
    b = clamp_int(c + half_width, lo, hi)
    if a > b:
        a, b = b, a
    if a == b and a < hi:
        b = a + 1
    return a, b

# ----------------------------
# main
# ----------------------------
def main():
    ap = argparse.ArgumentParser(description="Generate workload SQL with equality and range queries for a single-column table.")
    ap.add_argument("--table", default="salary", help="Target table name")
    ap.add_argument("--column", default="salary", help="Target column name")
    ap.add_argument("--out", default="workload_100.sql", help="Output .sql path")
    ap.add_argument("--n-equality", type=int, default=50, help="Number of equality queries")
    ap.add_argument("--n-range", type=int, default=50, help="Number of range queries")
    ap.add_argument("--min", dest="vmin", type=int, default=30000, help="Domain min (inclusive)")
    ap.add_argument("--max", dest="vmax", type=int, default=300000, help="Domain max (inclusive)")
    ap.add_argument("--seed", type=int, default=42, help="Random seed")
    ap.add_argument(
        "--mix",
        default="uniform:0.25,normal:0.2,laplace:0.15,student_t:0.1,lognormal:0.15,pareto:0.075,zipf:0.075",
        help="Distribution mix 'name:weight,...' (names: uniform,normal,laplace,student_t,lognormal,pareto,zipf)",
    )
    args = ap.parse_args()

    rng = np.random.default_rng(args.seed)
    names, probs = parse_mix(args.mix)

    lo, hi = args.vmin, args.vmax
    mid = (lo + hi) / 2.0
    span = hi - lo

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append(f"-- Workload generated by make_workload.py")
    lines.append(f"-- Table: {args.table}, Column: {args.column}")
    lines.append(f"-- Domain: [{lo}, {hi}], Seed: {args.seed}")
    lines.append(f"-- Mix: {args.mix}")
    lines.append("")

    # Equality queries
    for i in range(args.n_equality):
        k = choose_dist(rng, names, probs)
        dist = names[k]
        val = sample_value(dist, rng, lo, hi, mid, span)
        lines.append(f"-- EQ {i+1:02d}: dist={dist}, value={val}")
        lines.append(f"SELECT COUNT(*) FROM {args.table} WHERE {args.column} = {val};")
        lines.append("")

    # Range queries
    for i in range(args.n_range):
        k = choose_dist(rng, names, probs)
        dist = names[k]
        a, b = sample_range(dist, rng, lo, hi, mid, span)
        lines.append(f"-- RANGE {i+1:02d}: dist={dist}, low={a}, high={b}")
        lines.append(f"SELECT COUNT(*) FROM {args.table} WHERE {args.column} BETWEEN {a} AND {b};")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[done] wrote {args.n_equality + args.n_range} queries to {out_path}")

if __name__ == "__main__":
    main()
