import numpy as np
import csv
from pathlib import Path
from typing import List

class RangeQuery:
    def __init__(self, low: int, high: int):
        self.low = low
        self.high = high

    def to_dict(self):
        return {"low": int(self.low), "high": int(self.high)}

    @staticmethod
    def from_dict(d):
        return RangeQuery(int(d["low"]), int(d["high"]))

def generate_workload(n: int, mn: int, mx: int, seed: int = 42) -> List[RangeQuery]:
    rng = np.random.default_rng(seed)
    queries = []
    width = mx - mn
    for _ in range(n):
        l = rng.integers(mn, mx)
        # Random width up to 5% of domain
        w = rng.integers(1, max(10, width // 20)) 
        r = min(mx, l + w)
        queries.append(RangeQuery(l, r))
    return queries

def save_workload_csv(queries: List[RangeQuery], output_path: Path):
    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["low", "high"])
        for q in queries:
            writer.writerow([q.low, q.high])

def load_workload_csv(input_path: Path) -> List[RangeQuery]:
    queries = []
    with open(input_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            queries.append(RangeQuery(int(row["low"]), int(row["high"])))
    return queries

def main():
    workload_dir = Path("workload")
    workload_dir.mkdir(parents=True, exist_ok=True)
    
    # Independent workload generation
    # Fixed domain as requested (implied from previous context or standardizing on the default 200k domain)
    # Using 200,000 as the max domain based on the default "zipf" distribution generated by datasets.py
    MN, MX = 0, 200000 
    
    query_counts = [1000, 100000, 1000000]
    
    for count in query_counts:
        print(f"Generating independent workload: {count} queries for domain [{MN}, {MX}]...")
        queries = generate_workload(count, MN, MX)
        out_path = workload_dir / f"{count}.csv"
        save_workload_csv(queries, out_path)
        print(f"Saved to {out_path}")

if __name__ == "__main__":
    main()
